% this routine re-organizes the Lake Erie data in station-wise format and
% combines water quality and physical attributes data
% Note 1: PhyAtt file contains data at different depths; WQ file does not
% contain data at different depths
% Note 2: Accordingly, num of columns needs to be changed in the code below
% when these WQ and PhyAtt files are read

clear all
close all        
clc

direc='D:/Research/EPA_Project/Lake_Erie_HAB/Data/lake_erie_LEC';

% column list in the text-file
col_list={'Lookup',...
    'Date/Time'...
    'Station_ID',...
    'wtemp(deg C)',...
    'spcond(us/cm)',...
    'do(mg/L)',...
    'ph()',...
    'turb(NTU)',...
    'fluor(øC)',...
    'chl-fluor(ug/L)',...
    'bga-pc1(cells/ml)',...
    'bga-pc2(RFU)',...
    'kpar(1/m)',...
    'secchi(cm)',...
    'chl-ext(ug/L)',...
    'tss(mg/L)',...
    'vss(mg/L)',...
    'nh3(mg/L)',...
    'cl(mg/L)',...
    'so4(mg/L)',...
    'no2(mg/L)',...
    'no3(mg/L)',...
    'sio2(mg/L)',...
    'srp(mg/L)',...
    'tp(mg/L)',...
    'tkn(mg/L)',...
    'f(mg/L)',...
    'tsp(mg/L)',...
    'biovolume(ml/m2)',...
    'microcystin(ug/L)',...
    'dosat(%)',...
    'alg-grn(ug/L)',...
    'alg-bg(ug/L)',...
    'alg-dia(ug/L)',...
    'alg-cryp(ug/L)',...
    'alg-tot(ug/L)',...
    'tds(mg/L)'};

% station list
station_list={'CRIB','4P','7M','8M','GR1',...
    'MB18','MB20','BUOY','OREGON'};

% read the WQ data from text-file
folder='LEC-WLEB_download';
fname='LEC-WLEB_monitoring_WQ.txt';
filename=fullfile(direc,folder,fname);
formatspec=strcat('%s%s%s',...
    repmat('%f',1,37));
fid=fopen(filename,'r');
data=textscan(fid,formatspec,'delimiter','\t','headerlines',1);
fclose(fid);

date_time=data{2};
station=data{3};
param=cat(2,data{4:37});

% separate date and time data
date=cell(length(date_time),1);
time=cell(length(date_time),1);
for ind=1:length(date_time)
    date_time_split=strsplit(date_time{ind},char(32));
    date{ind}=date_time_split{1};
    time{ind}=date_time_split{2};
end

% arrange the data according to stations and write into text-files
unique_stations=unique(station);
for station_ind=1:length(unique_stations)
    
    % read data corresponding to a station in 'unique_stations'
    temp_station=unique_stations{station_ind};
    ind=strcmp(station,temp_station);
    write_date=date(ind);
    write_time=time(ind);
    write_param=param(ind,:);
    
    % write data to text-files
    wfname=strcat('WQ_',unique_stations{station_ind});
    wfilename=fullfile(direc,wfname);
    wformatspec=strcat('%s\t%s\t',...
        repmat('%f\t',1,33),'%f\n');
    wfid=fopen(wfilename,'w');
    fprintf(wfid,strcat(repmat('%s\t',1,35),'%s\n'),'date','time',col_list{4:37});
    
    for w_ind=1:length(write_date)
        fprintf(wfid,wformatspec,write_date{w_ind},write_time{w_ind},write_param(w_ind,:));
    end
    fclose(wfid);
    
end